site_name: OpenProject on RPi Install Documentation
repo_url: https://github.com/creeper-0910/OpenProjectRaspberryPi4B
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.expand


nav:
  - Introduction:
    - index.md
  - Build:
    - build/index.en.md
    - build/dependence.en.md
    - build/build.en.md
  - Troubleshooting:
    - troubleshooting/index.en.md

plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        ja: 日本語
      nav_translations:
        ja:
          site_name: RPi4 OpenProjectインストールドキュメント
          Introduction: はじめに
          Build: ビルド
          Dependence: 依存関係
          Index: 索引
          Troubleshooting: トラブルシューティング
        